import type { Locale } from '../i18n';

export interface GoPlanCampaignCopy {
  eyebrow: string;
  headline: string;
  description: string;
  benefit: string;
  status: string;
  cta: string;
  renewal: string;
  boundary: string;
  newBadge: string;
  closeAria: string;
  providersAria: string;
  workbenchBadge: string;
  workbenchBadgeAria: string;
}

const english: GoPlanCampaignCopy = {
  eyebrow: 'NEW PLAN · LAUNCH OFFER',
  headline: 'Low-cost design plan for everyone',
  description: 'Professional design intelligence at a lower cost—so every idea moves faster from prompt to finished work.',
  benefit: 'Go first month $5 · unlimited use',
  status: 'UNLIMITED',
  cta: 'View Go plan · Limited-time 50% off',
  renewal: 'Then $10 / month',
  boundary: 'Allowance details and offer terms are shown on Pricing.',
  newBadge: 'NEW',
  closeAria: 'Close dialog',
  providersAria: 'Model providers available on Go',
  workbenchBadge: 'The new Go Plan · ¥5 for the first month · Unlimited model usage',
  workbenchBadgeAria: 'The new Go Plan, ¥5 for the first month, unlimited model usage — view Pricing',
};

const localized: Record<Locale, GoPlanCampaignCopy> = {
  en: english,
  id: {
    eyebrow: 'PAKET BARU · PENAWARAN PELUNCURAN',
    headline: 'Kenali Go: lebih leluasa untuk terus berkarya.',
    description: 'Paket ringan untuk desain dan coding sehari-hari, dengan model populer siap digunakan.',
    benefit: 'Go bulan pertama $5 · penggunaan tanpa batas',
    status: 'TANPA BATAS',
    cta: 'Lihat paket Go',
    renewal: 'Lalu $10 / bulan',
    boundary: 'Detail kuota dan ketentuan penawaran ditampilkan di halaman Harga.',
    newBadge: 'BARU',
    closeAria: 'Tutup dialog',
    providersAria: 'Penyedia model yang tersedia di Go',
    workbenchBadge: 'Go bulan pertama $5 · tanpa batas',
    workbenchBadgeAria: 'Go bulan pertama $5, penggunaan tanpa batas — lihat Harga',
  },
  de: {
    eyebrow: 'NEUER TARIF · STARTANGEBOT',
    headline: 'Lerne Go kennen: mehr Freiraum, um kreativ zu bleiben.',
    description: 'Ein leichter Tarif für alltägliches Design und Coding, mit beliebten Modellen direkt einsatzbereit.',
    benefit: 'Go im ersten Monat $5 · unbegrenzte Nutzung',
    status: 'UNBEGRENZT',
    cta: 'Go-Tarif ansehen',
    renewal: 'Danach $10 / Monat',
    boundary: 'Kontingentdetails und Angebotsbedingungen stehen auf der Preisseite.',
    newBadge: 'NEU',
    closeAria: 'Dialog schließen',
    providersAria: 'In Go verfügbare Modellanbieter',
    workbenchBadge: 'Go: erster Monat $5 · unbegrenzt',
    workbenchBadgeAria: 'Go: erster Monat $5, unbegrenzte Nutzung — Preise ansehen',
  },
  'zh-CN': {
    eyebrow: '全新套餐 · 首发特惠',
    headline: '人人可用的低成本设计方案',
    description: '以更低成本使用专业设计模型，让每一个想法更快成为作品。',
    benefit: 'Go 首月 $5 · 无限用',
    status: '无限使用',
    cta: '查看 Go 套餐 · 限时 5 折',
    renewal: '之后 $10 / 月',
    boundary: '具体额度与活动规则以 Pricing 页面为准。',
    newBadge: 'NEW',
    closeAria: '关闭弹窗',
    providersAria: 'Go 套餐可用模型厂商',
    workbenchBadge: '全新 Go 套餐 · 首月 ¥5 · 模型无限用',
    workbenchBadgeAria: '全新 Go 套餐，首月 ¥5，模型无限用，查看 Pricing',
  },
  'zh-TW': {
    eyebrow: '全新方案 · 首發優惠',
    headline: 'Go，讓靈感不中斷。',
    description: '適合日常設計與編碼的輕量方案，熱門模型開箱即用。',
    benefit: 'Go 首月 $5 · 無限用',
    status: '無限使用',
    cta: '查看 Go 方案',
    renewal: '之後 $10 / 月',
    boundary: '具體額度與活動規則以 Pricing 頁面為準。',
    newBadge: 'NEW',
    closeAria: '關閉彈窗',
    providersAria: 'Go 方案可用的模型供應商',
    workbenchBadge: 'Go 首月 $5 · 無限用',
    workbenchBadgeAria: 'Go 首月 5 美元，無限用，查看 Pricing',
  },
  'pt-BR': {
    eyebrow: 'NOVO PLANO · OFERTA DE LANÇAMENTO',
    headline: 'Conheça o Go: mais espaço para continuar criando.',
    description: 'Um plano mais leve para design e programação do dia a dia, com modelos populares prontos para usar.',
    benefit: 'Go no primeiro mês por $5 · uso ilimitado',
    status: 'ILIMITADO',
    cta: 'Ver plano Go',
    renewal: 'Depois, $10 / mês',
    boundary: 'Os detalhes da franquia e os termos da oferta estão na página de preços.',
    newBadge: 'NOVO',
    closeAria: 'Fechar caixa de diálogo',
    providersAria: 'Provedores de modelos disponíveis no Go',
    workbenchBadge: 'Go no primeiro mês por $5 · uso ilimitado',
    workbenchBadgeAria: 'Go no primeiro mês por $5, uso ilimitado — ver preços',
  },
  'es-ES': {
    eyebrow: 'PLAN NUEVO · OFERTA DE LANZAMIENTO',
    headline: 'Conoce Go: más espacio para seguir creando.',
    description: 'Un plan más ligero para el diseño y la programación diarios, con modelos populares listos para usar.',
    benefit: 'Go el primer mes por $5 · uso ilimitado',
    status: 'ILIMITADO',
    cta: 'Ver el plan Go',
    renewal: 'Después, $10 / mes',
    boundary: 'Los detalles de la cuota y las condiciones de la oferta se muestran en la página de precios.',
    newBadge: 'NUEVO',
    closeAria: 'Cerrar diálogo',
    providersAria: 'Proveedores de modelos disponibles en Go',
    workbenchBadge: 'Go el primer mes por $5 · uso ilimitado',
    workbenchBadgeAria: 'Go el primer mes por $5, uso ilimitado — ver precios',
  },
  ru: {
    eyebrow: 'НОВЫЙ ТАРИФ · СТАРТОВОЕ ПРЕДЛОЖЕНИЕ',
    headline: 'Знакомьтесь с Go: больше возможностей творить без остановки.',
    description: 'Облегчённый тариф для повседневного дизайна и программирования с популярными моделями, готовыми к работе.',
    benefit: 'Первый месяц Go за $5 · безлимитное использование',
    status: 'БЕЗ ЛИМИТОВ',
    cta: 'Посмотреть тариф Go',
    renewal: 'Затем $10 / месяц',
    boundary: 'Подробности о лимитах и условиях предложения указаны на странице тарифов.',
    newBadge: 'НОВИНКА',
    closeAria: 'Закрыть диалог',
    providersAria: 'Поставщики моделей, доступные в Go',
    workbenchBadge: 'Go: первый месяц за $5 · без лимитов',
    workbenchBadgeAria: 'Go: первый месяц за $5, безлимитное использование — открыть тарифы',
  },
  fa: {
    eyebrow: 'طرح جدید · پیشنهاد آغازین',
    headline: 'با Go آشنا شوید: فضای بیشتری برای ادامه خلاقیت.',
    description: 'طرحی سبک‌تر برای طراحی و کدنویسی روزمره، با مدل‌های محبوب آماده استفاده.',
    benefit: 'ماه اول Go با ۵ دلار · استفاده نامحدود',
    status: 'نامحدود',
    cta: 'مشاهده طرح Go',
    renewal: 'پس از آن ۱۰ دلار / ماه',
    boundary: 'جزئیات سهمیه و شرایط پیشنهاد در صفحه قیمت‌گذاری نمایش داده می‌شود.',
    newBadge: 'جدید',
    closeAria: 'بستن پنجره',
    providersAria: 'ارائه‌دهندگان مدل موجود در Go',
    workbenchBadge: 'Go ماه اول ۵ دلار · استفاده نامحدود',
    workbenchBadgeAria: 'Go با ۵ دلار برای ماه اول، استفاده نامحدود — مشاهده قیمت‌ها',
  },
  ar: {
    eyebrow: 'خطة جديدة · عرض الإطلاق',
    headline: 'تعرّف على Go: مساحة أكبر لمواصلة الإبداع.',
    description: 'خطة أخف للتصميم والبرمجة اليومية، مع نماذج شائعة جاهزة للاستخدام.',
    benefit: 'Go للشهر الأول مقابل 5 دولارات · استخدام غير محدود',
    status: 'غير محدود',
    cta: 'عرض خطة Go',
    renewal: 'ثم 10 دولارات / شهريًا',
    boundary: 'تظهر تفاصيل الحصة وشروط العرض في صفحة الأسعار.',
    newBadge: 'جديد',
    closeAria: 'إغلاق مربع الحوار',
    providersAria: 'موفرو النماذج المتاحون في Go',
    workbenchBadge: 'Go للشهر الأول مقابل 5 دولارات · استخدام غير محدود',
    workbenchBadgeAria: 'Go للشهر الأول مقابل 5 دولارات، استخدام غير محدود — عرض الأسعار',
  },
  ja: {
    eyebrow: '新プラン · ローンチ特典',
    headline: 'Goで、創作をもっと自由に。',
    description: '日々のデザインとコーディングに適した軽量プラン。人気モデルをすぐに使えます。',
    benefit: 'Go 初月 $5 · 無制限で利用',
    status: '無制限',
    cta: 'Goプランを見る',
    renewal: '以降 $10 / 月',
    boundary: '利用枠の詳細とキャンペーン条件は料金ページに表示されます。',
    newBadge: '新着',
    closeAria: 'ダイアログを閉じる',
    providersAria: 'Goで利用できるモデルプロバイダー',
    workbenchBadge: 'Go 初月 $5 · 無制限',
    workbenchBadgeAria: 'Go 初月 $5、無制限で利用 — 料金を見る',
  },
  ko: {
    eyebrow: '새 요금제 · 출시 혜택',
    headline: 'Go로 더 여유롭게 창작을 이어가세요.',
    description: '일상적인 디자인과 코딩을 위한 가벼운 요금제로, 인기 모델을 바로 사용할 수 있습니다.',
    benefit: 'Go 첫 달 $5 · 무제한 사용',
    status: '무제한',
    cta: 'Go 요금제 보기',
    renewal: '이후 월 $10',
    boundary: '사용량 세부 정보와 혜택 조건은 요금 페이지에서 확인할 수 있습니다.',
    newBadge: '신규',
    closeAria: '대화 상자 닫기',
    providersAria: 'Go에서 사용할 수 있는 모델 제공업체',
    workbenchBadge: 'Go 첫 달 $5 · 무제한',
    workbenchBadgeAria: 'Go 첫 달 $5, 무제한 사용 — 요금 보기',
  },
  pl: {
    eyebrow: 'NOWY PLAN · OFERTA STARTOWA',
    headline: 'Poznaj Go: więcej swobody, by tworzyć bez przerwy.',
    description: 'Lżejszy plan do codziennego projektowania i programowania, z popularnymi modelami gotowymi do użycia.',
    benefit: 'Go: pierwszy miesiąc za $5 · bez limitu',
    status: 'BEZ LIMITU',
    cta: 'Zobacz plan Go',
    renewal: 'Potem $10 / miesiąc',
    boundary: 'Szczegóły limitów i warunki oferty znajdują się na stronie cennika.',
    newBadge: 'NOWOŚĆ',
    closeAria: 'Zamknij okno dialogowe',
    providersAria: 'Dostawcy modeli dostępni w Go',
    workbenchBadge: 'Go pierwszy miesiąc $5 · bez limitu',
    workbenchBadgeAria: 'Go pierwszy miesiąc za $5, bez limitu — zobacz cennik',
  },
  hu: {
    eyebrow: 'ÚJ CSOMAG · BEVEZETŐ AJÁNLAT',
    headline: 'Ismerd meg a Gót: több tér az alkotás folytatásához.',
    description: 'Könnyebb csomag mindennapi tervezéshez és kódoláshoz, használatra kész népszerű modellekkel.',
    benefit: 'Go első hónap $5 · korlátlan használat',
    status: 'KORLÁTLAN',
    cta: 'Go csomag megtekintése',
    renewal: 'Utána $10 / hó',
    boundary: 'A keret részletei és az ajánlat feltételei az árak oldalán találhatók.',
    newBadge: 'ÚJ',
    closeAria: 'Párbeszédablak bezárása',
    providersAria: 'A Go csomagban elérhető modellszolgáltatók',
    workbenchBadge: 'Go első hónap $5 · korlátlanul',
    workbenchBadgeAria: 'Go első hónap $5, korlátlan használat — árak megtekintése',
  },
  fr: {
    eyebrow: 'NOUVELLE FORMULE · OFFRE DE LANCEMENT',
    headline: 'Découvrez Go : plus de liberté pour continuer à créer.',
    description: 'Une formule légère pour le design et le code au quotidien, avec des modèles populaires prêts à l’emploi.',
    benefit: 'Premier mois de Go à 5 $ · usage illimité',
    status: 'ILLIMITÉ',
    cta: 'Voir la formule Go',
    renewal: 'Puis 10 $ / mois',
    boundary: 'Les détails du quota et les conditions de l’offre figurent sur la page des tarifs.',
    newBadge: 'NOUVEAU',
    closeAria: 'Fermer la boîte de dialogue',
    providersAria: 'Fournisseurs de modèles disponibles avec Go',
    workbenchBadge: 'Go : premier mois à 5 $ · usage illimité',
    workbenchBadgeAria: 'Go : premier mois à 5 $, usage illimité — voir les tarifs',
  },
  uk: {
    eyebrow: 'НОВИЙ ПЛАН · СТАРТОВА ПРОПОЗИЦІЯ',
    headline: 'Знайомтеся з Go: більше простору для безперервної творчості.',
    description: 'Полегшений план для щоденного дизайну й програмування з популярними моделями, готовими до роботи.',
    benefit: 'Перший місяць Go за $5 · безлімітне використання',
    status: 'БЕЗ ОБМЕЖЕНЬ',
    cta: 'Переглянути план Go',
    renewal: 'Потім $10 / місяць',
    boundary: 'Докладні ліміти й умови пропозиції наведено на сторінці цін.',
    newBadge: 'НОВИНКА',
    closeAria: 'Закрити діалогове вікно',
    providersAria: 'Постачальники моделей, доступні в Go',
    workbenchBadge: 'Go: перший місяць за $5 · без обмежень',
    workbenchBadgeAria: 'Go: перший місяць за $5, безлімітне використання — переглянути ціни',
  },
  tr: {
    eyebrow: 'YENİ PLAN · LANSMAN TEKLİFİ',
    headline: 'Go ile tanışın: üretmeye devam etmek için daha fazla alan.',
    description: 'Günlük tasarım ve kodlama için, popüler modelleri kullanıma hazır daha hafif bir plan.',
    benefit: 'Go ilk ay $5 · sınırsız kullanım',
    status: 'SINIRSIZ',
    cta: 'Go planını görüntüle',
    renewal: 'Sonrasında aylık $10',
    boundary: 'Kota ayrıntıları ve teklif koşulları Fiyatlandırma sayfasında gösterilir.',
    newBadge: 'YENİ',
    closeAria: 'İletişim kutusunu kapat',
    providersAria: "Go'da kullanılabilen model sağlayıcıları",
    workbenchBadge: 'Go ilk ay $5 · sınırsız kullanım',
    workbenchBadgeAria: 'Go ilk ay $5, sınırsız kullanım — fiyatları görüntüle',
  },
  th: {
    eyebrow: 'แพ็กเกจใหม่ · ข้อเสนอช่วงเปิดตัว',
    headline: 'รู้จัก Go: พื้นที่มากขึ้นเพื่อสร้างสรรค์ได้อย่างต่อเนื่อง',
    description: 'แพ็กเกจเบาสำหรับงานออกแบบและเขียนโค้ดในทุกวัน พร้อมโมเดลยอดนิยมที่ใช้ได้ทันที',
    benefit: 'Go เดือนแรก $5 · ใช้งานไม่จำกัด',
    status: 'ไม่จำกัด',
    cta: 'ดูแพ็กเกจ Go',
    renewal: 'จากนั้น $10 / เดือน',
    boundary: 'รายละเอียดโควตาและเงื่อนไขข้อเสนอแสดงอยู่ในหน้าราคา',
    newBadge: 'ใหม่',
    closeAria: 'ปิดกล่องโต้ตอบ',
    providersAria: 'ผู้ให้บริการโมเดลที่ใช้ได้ใน Go',
    workbenchBadge: 'Go เดือนแรก $5 · ใช้งานไม่จำกัด',
    workbenchBadgeAria: 'Go เดือนแรก $5 ใช้งานไม่จำกัด — ดูราคา',
  },
  it: {
    eyebrow: 'NUOVO PIANO · OFFERTA DI LANCIO',
    headline: 'Scopri Go: più spazio per continuare a creare.',
    description: 'Un piano più leggero per il design e la programmazione di ogni giorno, con modelli popolari pronti all’uso.',
    benefit: 'Go primo mese a $5 · uso illimitato',
    status: 'ILLIMITATO',
    cta: 'Vedi il piano Go',
    renewal: 'Poi $10 / mese',
    boundary: 'I dettagli della quota e le condizioni dell’offerta sono riportati nella pagina dei prezzi.',
    newBadge: 'NOVITÀ',
    closeAria: 'Chiudi finestra di dialogo',
    providersAria: 'Provider di modelli disponibili con Go',
    workbenchBadge: 'Go primo mese $5 · uso illimitato',
    workbenchBadgeAria: 'Go primo mese a $5, uso illimitato — vedi i prezzi',
  },
};

export function getGoPlanCampaignCopy(locale: Locale): GoPlanCampaignCopy {
  return localized[locale];
}
